class AutologyError(Exception):
    """
    Exception class for the :py:mod:`insights.util.autology` module
    """
    pass
